### ISSUE TITLE
Insertion operator (<<) of the products

### ISSUE THREAD

**Issue by TolikPylypchuk** [lhalam/firstProject1415#2]
The insertion operator of the base Product class is ok, but it's not ok in all derived classes. It must not insert the name of the field that is inserted, only its value. For example:
`stream << "name: " << product.name;` is incorrect. It mustn't insert `"name: "`
`stream << product.name << ' ';` is correct. (Don't forget about the spaces between the values.)
That's because this operator will be used with file streams. If you need to print info about product to the screen, use some special function, for example, `print`.

**Comment by YaroslavKormushyn** [comment]
Thanks for the tip.
We've decided to use the '\n' or <endl> separator between different info fields.
If it's significant to use spaces, please reply at your earliest convenience.

**Comment by TolikPylypchuk** [comment]
No, it's not significant, what whitespace character you use, as long as it works correctly :)

**Comment by NataliaSlobodianiuk** [comment]
let's use endl then
