### ISSUE TITLE
Operator >> in class User

### ISSUE THREAD

**Issue by TolikPylypchuk** [lhalam/firstProject1415#3]
There mustn't be any cout calls in this operator. This operator is used to work with files. To work with console, you need to create a separate function, `print` for example.

**Comment by YaroslavKormushyn** [comment]
Added Output/Input methods specially for command prompt.
Changed << and >> operator overloads.
3rd ierarchy level classes - the change still pending.
Will have been finished by wednesday.

**Comment by mykolivy** [comment]
Totally agree

**Comment by YaroslavKormushyn** [comment]
If this issue is not closed by the adressee until Tuesday, _I'll have to close it_ as resolved.
