### ISSUE TITLE
#learn to use include

### ISSUE THREAD

**Issue by mykolivy** [lhalam/firstProject1415#5]
Why is there an #include of Message.h in Product.h?
You dont use class Message in that file.
You block me from including Prouct.h in Message.h, where i need it.
Only include things when you are going to use them

**Comment by YaroslavKormushyn** [comment]
Sorry for interrupting your flaming, but I need Message.h in Product.cpp
In particular, I use it in output and input methods for command prompt manipulations.
Regards.

**Comment by mykolivy** [comment]
So... What is the problem?
Just include Message.h in your Product.cpp.

**Comment by YaroslavKormushyn** [comment]
If the whole product ierarchy needs Message.h, why do i have to include that file every time a new header is created?
Isn't it more simple to include Message.h in the top class'es (not sure whether it's spelled like this) header?

**Comment by mykolivy** [comment]
Yes, yo **DO** have to include that file only where you **USE** it.
Yes, it is more simple to include only once, but this is incorrect.
Why?
As an example: I need to include Product.h in my Message.h, but i cant do that because you have included my file in your Product.h and DONT use it. You only block me.

**Comment by YaroslavKormushyn** [comment]
I don't agree that this was the right decision, but I included `Message.h` in all the `.cpp` files and deleted 'em from `.h` files.
Regards.
