### ISSUE TITLE
Functions 'Without functionality' And other stuff

### ISSUE THREAD

**Issue by mykolivy** [lhalam/firstProject1415#6]
**PLEASE**
Try to compile the code that you have written. Check if there are mistakes.
**DON'T** push code that has errors. **PLEASE**

**Comment by TolikPylypchuk** [comment]
If you're referring to the function I've written (because I've added the 'without functionality' comment), than I must say that I just forgot to write a `return` statement in it. I've already pushed the changes so now it works.
Sorry for the inconvenience. I hope it won't happen again.

**Comment by mykolivy** [comment]
No its not.
In fact it is just my plea for checking your code.
