### ISSUE TITLE
Id

### ISSUE THREAD

**Issue by mykolivy** [lhalam/firstProject1415#7]
When we create a new user or product their IDs must be generated by our program, not by user's input.

My suggestion is to assign each id a unix timestamp of the time the new user/product is created.
This will guarantee the unicity of each id.

**Comment by NataliaSlobodianiuk** [comment]
We've already thought about that, the idea was in generating random ids.
But your idea is the one I liked more.

2015-04-13 19:30 GMT+03:00 Marakaido notifications@github.com:
