### ISSUE TITLE
Database (thoughts)

### ISSUE THREAD

**Issue by mykolivy** [lhalam/firstProject1415#8]
I have an idea of how to make our database better (or not).

For example, we have one file for information about all users.
We also need file for each user to save the history of his purchases.
Maybe in future we will need another file for each user to display information regarding a particular user.

So i thought: "Why dont we create a folder with the name 'id of the user' and put all the files regarding this user into it?"
There will be some changes:
1. There will not be any file that will have the information about all the users
2. User's information will be displayed in a 'UserData.txt' in user's folder

This will simplify lots of things. 
Hope you will like my idea.

**Comment by NataliaSlobodianiuk** [comment]
So how, in this way, the command "showAllUsers" works? It just
displays 'UserData.txt'
from each user's folder? It may be OK then.

2015-04-13 20:49 GMT+03:00 Marakaido notifications@github.com:

**Comment by YaroslavKormushyn** [comment]
I definitely like it, unless you don't have any idea how the program would move between folders, which names should be, obviously, unique unix stamps?

**Comment by mykolivy** [comment]
Definitely, i have another, simpler idea.
We should keep the file with the information about all the users. We will keep it outside all user folders.
And other files we will keep in these folders.
